<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>


    <LangVersion>preview</LangVersion>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
	<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
	<RootNamespace>Easy_Copier</RootNamespace>
	<ApplicationManifest>app.manifest</ApplicationManifest>
	<Platforms>x86;x64;ARM64</Platforms>
	<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
	<UseWinUI>true</UseWinUI>
	<WinUISDKReferences>false</WinUISDKReferences>
	<Nullable>enable</Nullable>
	<EnableMsixTooling>true</EnableMsixTooling>
	<WindowsPackageType Condition="'$(WindowsPackageType)' == ''">None</WindowsPackageType>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="Assets\easy copier ico - Copy.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\SplashScreen.scale-200.png" />
    <Content Include="Assets\LockScreenLogo.scale-200.png" />
    <Content Include="Assets\Square150x150Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.scale-200.png" />
    <Content Include="Assets\Square44x44Logo.targetsize-24_altform-unplated.png" />
    <Content Include="Assets\StoreLogo.png" />
    <Content Include="Assets\Wide310x150Logo.scale-200.png" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.WinUI.Extensions" Version="8.2.251219" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.11" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
    <PackageReference Include="System.Management" Version="10.0.11" />
  <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.11" /><PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" /></ItemGroup>

  <ItemGroup>
    <Content Include="Assets\easy copier ico.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>

  </ItemGroup>

  <PropertyGroup>
    <DefineConstants>DISABLE_XAML_GENERATED_MAIN</DefineConstants>

    <PublishReadyToRun>false</PublishReadyToRun>
    <PublishTrimmed>False</PublishTrimmed>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <ApplicationIcon>Assets\easy copier ico.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
<PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
</Project>