name: Build and Test Easy-Copier

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' 

      # Quotes added around the file name to handle the space
      - name: Restore the application
        run: msbuild "$env:Solution_Name" /t:Restore /p:Configuration=$env:Configuration

      
      - name: Restore Dependencies
        run: dotnet restore "Easy Copier.slnx"

      - name: Run Tests
        run: dotnet test "Easy Copier.slnx" --configuration Release --no-restore

      - name: Compile Application
        run: dotnet build "Easy Copier.slnx" --configuration Release --runtime win-x64 --no-restore
